### PR TITLE
(collab) jobs to toggle elgg cron

### LINKED ISSUE #2016: Gccollab digest not working
As a user of Gccollab, I need the daily digest to be notified of updates.

Several users are reporting that the digest emails are not being sent out. Resetting their notification options did not help.

Users who reported this issue:
alana.johnson@hrsdc-rhdcc.gc.ca
nick.schonning@cic.gc.ca
konstantinmanyakin@cmail.carleton.ca
chenaitukiso.muzondo@servicecanada.gc.ca
guillaume.faubert@canada.ca

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

### PR DESCRIPTION
**Pull request by Phanoix**
Better than every instance toggling things like db cleanup.

closes gctools-outilsgc/gcconnex#2016

### CODE REVIEW

**Comment by nschonni** [comment]
@Phanoix did this get autodeployed, or is it waiting for a release?

**Comment by Phanoix** [comment]
I wanted to manually trigger these the first time since they haven't run for some time, it's up now.

**Comment by nschonni** [comment]
OK, still not seeing digests from GCcollab, so some of those issues you closed might need to re-open

**Comment by nschonni** [comment]
if you give the time when you manually triggered, or when it actually ran through the cron, I can ask SSC to see if it even reached the mail gateway

**Comment by Phanoix** [comment]
I watched both the weekly and daily digests being processed and sent out server side so that part's working properly again at least. Client side seems to vary a fair bit with emails going through or not though.. I've been receiving the daily digests since the weekend and before the first weekly one triggered I changed mine to weekly and got that one too but I know for some departments email from collab have trouble getting  through.

**Comment by nschonni** [comment]
if you let me know the times it was supposed to go through I can confirm with SSC. I haven't gotten digests in 6+ months. I've previously confirmed with SSC, that there is nothing getting to the mailrelay, so it's was not a spam filter issue.

**Comment by Phanoix** [comment]
Starting this week they should be coming it at 1 am for daily and midnight for weekly ones (EDT). I triggered them manually later than that over the weekend but aside from that they should come within a few minutes of those times.

**Pull request merged**
